name: Build and Publish Docker Image

on: 
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      ## checks out our project source code
      - uses: actions/checkout@v3
      ## Builds our docker image!
      - name: Build Docker Image 
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      ## Publishes our image to Docker Hub
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          # github username / repository name
          name: akashjs/go-github-actions
          ## Here we pass in our Docker Username and Password
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Secret should be added to the git repository
          # Navigate to the repo settings --> secret --> actions --> add new repo secret