name: Build and Publish Docker Image

on: 
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image 
        run: docker build . --tag my-image-name:$(date +%s)

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: jsakash/go-github-actions

          ## Here we pass in our Docker Username
          username: ${{ secrets.DOCKER_USERNAME }}
          ## and our Docker password which 
          password: ${{ secrets.DOCKER_PASSWORD }}