name: Test

# Specifiying branch where the action should take place 
on: 
  push:
    branches:
      - main

jobs:
  test:
    ## Defining strategy for our job
    strategy:
      matrix:
       ## this will contain a matrix of all of the combinations 
        go-version: [1.16.x, 1.17.x, 1.18.x]
        platform: [ubuntu-latest,  macos-latest, windows-latest]
    ## Defines the platform for each test run
    runs-on: ${{ matrix.platform }}
    ## the steps that will be run through for each version and platform
    ## combination
    steps:
    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: ${{matrix.go-version}}

    - uses: actions/checkout@v3

    - name: Test
      run: go test ./...