name: Test

on: 
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        platform: [ubuntu-latest,  mscos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: ${{matrix.go-version}}

    - uses: actions/checkout@v3

    - name: Test
      run: go test ./...